<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Understanding Life Expectancy and Health Disparities between Developed and Developing Countries</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Team 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html" rel="" target="">
 <span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf" rel="" target="">
 <span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" rel="" target="" aria-current="page">
 <span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data">Introduction and Data</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding Life Expectancy and Health Disparities between Developed and Developing Countries</h1>
<p class="subtitle lead">Team 2 Report</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-and-data" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-data">Introduction and Data</h2>
<p>The dataset is from the World Health Organization and has data on factors that relate to life expectancy, including mortality, immunization, and socioeconomic factors. As stated by the World Health Organization, data is collected through household surveys, civil registrations, and institutional sources such as health facilities. This data is then curated into the Global Health Observatory database. The dataset has data from all countries collected from 2000 to 2015. Each observation is a country’s health status for a given year, and it includes variables such as life expectancy, mortality rates, country development status, schooling, disease rates, and alcohol rates.</p>
<p>We conducted data cleaning by dropping all rows from the dataset that had N/A values. This was done so that the N/A values wouldn’t interfere with our data analysis.</p>
<p><strong>Research Question</strong></p>
<p>Question: Which health and socioeconomic factors most greatly affect the life expectancy of a country, and does this differ between developed and developing countries?</p>
<p>The research topic is life expectancy and the factors that influence it, as well as how these factors differ between countries. Our hypothesis is that developed countries will on average have higher life expectancy than developing countries, and that the factors most correlated with life expectancy are immunization coverage and income composition of resources. There are both categorical and quantitative variables involved in our research topic. Development status is a categorical variable and immunization coverage, income composition of resources, disease rates, mortality rates, and schooling are quantitative variables. Life expectancy is a quantitative variable.</p>
<p>By looking into life expectancy and the factors that underlie it, we hope to better understand the overall health profile of developed and developing countries. Understanding these differences can inform interventions aimed at reducing health inequalities, which governments and international organizations can utilize when shaping effective policies. Additionally, researching the predictors of life expectancy can drive scientific and medical innovation. It can lead to the development of new technologies, treatments, and preventive measures that are tailored to the unique health challenges faced by different populations. Also, knowledge of the predictors of life expectancy can be crucial for crisis preparedness, such as responding to pandemics, natural disasters, or other health emergencies. It allows for targeted and efficient responses to mitigate the impact on vulnerable populations.</p>
<p><strong>Literature</strong></p>
<p>The article from the World Health Organization provides a broad overview about the disparities in life expectancy between different countries. Although life expectancy fluctuated more in the 20th century due to political circumstances, it had largely stabilized (for most countries) by the turn of the 21st century. Globally, the life expectancy for children born in 2015 was 71.4 years. However, for high-income countries, life expectancy is closer to 80 years or more, and for low-income countries, life expectancy is under 60 years. Despite dramatic gains in life expectancy in the last two decades, these major inequalities still persist. This report focuses on access to health services as a major determining factor for a nation’s life expectancy. Complications with pregnancy and childbirth, HIV incidence, malaria outbreak, cardiovascular disease, cancer, lack of clean water, etc. represent just some of these risk factors that stem from or are exacerbated by underlying issues with healthcare infrastructure.</p>
<p>Our research question builds on the WHO article by determining which risk factors have the greatest, most direct impact on life expectancy for different countries. Additionally, the data set includes variables that are not directly mentioned in the article, so bringing more factors to the discussion regarding disparities in life expectancy provides us with a more nuanced outlook on the topic.</p>
<p><em>[“Life Expectancy Increases by 5 Years, but Inequalities Persist.” World Health Organization, World Health Organization, 19 May 2016, www.who.int/news/item/19-05-2016-life-expectancy-increased-by-5-years-since-2000-but-health-inequalities-persist.]</em></p>
<p><strong>Ethical Considerations</strong></p>
<p>Additionally, when considering the impact of socioeconomic and health factors on life expectancy across countries, it is crucial to consider ethical considerations of using such a health dataset. Primarily, an ethical concern is that the dataset provides information on sensitive health status of people such as HIV/AIDS status, alcohol consumption, mortality status, and life expectancy. Although the dataset contains sensitive health information, the dataset does not provide any information that would reveal the identity of the people surveyed.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,649
Columns: 22
$ Country                         &lt;chr&gt; "Afghanistan", "Afghanistan", "Afghani…
$ Year                            &lt;int&gt; 2015, 2014, 2013, 2012, 2011, 2010, 20…
$ Status                          &lt;chr&gt; "Developing", "Developing", "Developin…
$ Life.expectancy                 &lt;dbl&gt; 65.0, 59.9, 59.9, 59.5, 59.2, 58.8, 58…
$ Adult.Mortality                 &lt;int&gt; 263, 271, 268, 272, 275, 279, 281, 287…
$ infant.deaths                   &lt;int&gt; 62, 64, 66, 69, 71, 74, 77, 80, 82, 84…
$ Alcohol                         &lt;dbl&gt; 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.…
$ percentage.expenditure          &lt;dbl&gt; 71.279624, 73.523582, 73.219243, 78.18…
$ Hepatitis.B                     &lt;int&gt; 65, 62, 64, 67, 68, 66, 63, 64, 63, 64…
$ Measles                         &lt;int&gt; 1154, 492, 430, 2787, 3013, 1989, 2861…
$ BMI                             &lt;dbl&gt; 19.1, 18.6, 18.1, 17.6, 17.2, 16.7, 16…
$ under.five.deaths               &lt;int&gt; 83, 86, 89, 93, 97, 102, 106, 110, 113…
$ Polio                           &lt;int&gt; 6, 58, 62, 67, 68, 66, 63, 64, 63, 58,…
$ Total.expenditure               &lt;dbl&gt; 8.16, 8.18, 8.13, 8.52, 7.87, 9.20, 9.…
$ Diphtheria                      &lt;int&gt; 65, 62, 64, 67, 68, 66, 63, 64, 63, 58…
$ HIV.AIDS                        &lt;dbl&gt; 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1…
$ GDP                             &lt;dbl&gt; 584.25921, 612.69651, 631.74498, 669.9…
$ Population                      &lt;dbl&gt; 33736494, 327582, 31731688, 3696958, 2…
$ thinness..1.19.years            &lt;dbl&gt; 17.2, 17.5, 17.7, 17.9, 18.2, 18.4, 18…
$ thinness.5.9.years              &lt;dbl&gt; 17.3, 17.5, 17.7, 18.0, 18.2, 18.4, 18…
$ Income.composition.of.resources &lt;dbl&gt; 0.479, 0.476, 0.470, 0.463, 0.454, 0.4…
$ Schooling                       &lt;dbl&gt; 10.1, 10.0, 9.9, 9.8, 9.5, 9.2, 8.9, 8…</code></pre>
</div>
</div>
<p><strong>Summary Statistics</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 2
   name                                                    value
   &lt;chr&gt;                                                   &lt;dbl&gt;
 1 cor(Life.expectancy, HIV.AIDS)                        -0.592 
 2 cor(Life.expectancy, thinness..1.19.years)            -0.458 
 3 cor(Life.expectancy, thinness.5.9.years)              -0.458 
 4 cor(Life.expectancy, under.five.deaths)               -0.192 
 5 cor(Life.expectancy, infant.deaths)                   -0.169 
 6 cor(Life.expectancy, Measles)                         -0.0689
 7 cor(Life.expectancy, Population)                      -0.0223
 8 cor(Life.expectancy, Total.expenditure)                0.175 
 9 cor(Life.expectancy, Hepatitis.B)                      0.200 
10 cor(Life.expectancy, Polio)                            0.327 
11 cor(Life.expectancy, Diphtheria)                       0.341 
12 cor(Life.expectancy, Alcohol)                          0.403 
13 cor(Life.expectancy, percentage.expenditure)           0.410 
14 cor(Life.expectancy, GDP)                              0.441 
15 cor(Life.expectancy, BMI)                              0.542 
16 cor(Life.expectancy, Income.composition.of.resources)  0.721 
17 cor(Life.expectancy, Schooling)                        0.728 </code></pre>
</div>
</div>
<p>We began by calculating the correlation coefficient between each of the quantitative explanatory variables in the dataset and life expectancy. Correlation coefficient measures the strength and direction of a linear relationship between two variables. By calculating the correlation coefficient, we were able to identify which factors were the most highly associated with life expectancy.</p>
<p>The highest correlated variables are HIV/AIDs, Income Composition of Resources, and Schooling, which have correlation coefficients of -0.59, 0.72, and 0.73, respectively. The HIV/AIDs variable measures the deaths per 1,000 live births due to HIV/AIDS in a given year, the Income Composition of Resources variable is a score between 0 and 1 that measures how well a country utilizes its resources in a given year, and the Schooling variable is the number of years of schooling people in a country have on average in a given year.</p>
<p>Since we found that HIV/AIDs, Income Composition of Resources, and Schooling are the variables that are highest correlated with our response variable of life expectancy, we chose these variables to perform exploratory data analysis on.</p>
<p><strong>Exploratory Data Analysis</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/scatter-plot-ICOR-score-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>ICOR: As shown, there is a positive linear correlation between the ICOR score and life expectancy, and this relationship is true for developing and developed countries. In other words, as the ICOR score increases, the life expectancy increases in a linear manner for both developing and developed countries.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/HIV/AIDS-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>HIV/AIDS: As shown, there is a negative correlation between HIV/AIDS deaths per 1,000 births and life expectancy for developing countries. In other words, as HIV/AIDS deaths decrease, life expectancy increases, The graph also indicates that there is a low HIV/AIDS mortality in developed countries.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/schooling-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Schooling: As shown, there is a positive linear correlation between the years of schooling and life expectancy, and this relationship is true for developing and developed countries. In other words, as the number of years of schooling increases, the life expectancy increases in a linear manner for both developing and developed countries.</p>
<p><strong>Fitting Models</strong></p>
<p>Utilizing the explanatory analysis we conducted, we decided to fit a linear regression model to determine how predictive our selected factors, as well as country development status, were of life expectancy. We chose to fit a linear model based on the largely linear trends we saw between our chosen variables and life expectancy during exploratory data analysis. We fitted an additive model along with an interactive model. The additive model makes the assumption that all the factors have independent effects on life expectancy. For the interactive model, we chose to make the interactive term between Income Composition of Resources and country development status because these two variables are the most closely related to each other out of all the factors, and one is likely to influence the other.</p>
<p><em>Additive model:</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term                            estimate std.error statistic   p.value
  &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                       48.6      0.749      64.9  0        
2 Schooling                          1.19     0.0629     19.0  7.19e- 73
3 HIV.AIDS                          -0.631    0.0180    -35.1  4.14e-202
4 Income.composition.of.resources   13.9      0.939      14.8  1.89e- 46
5 StatusDeveloping                  -1.45     0.347      -4.18 3.09e-  5</code></pre>
</div>
</div>
<span class="math display">\[\begin{gather*}
\widehat{LifeExpectancy} = 48.56 + 1.195 * schooling - 0.63 * HIV/AIDS \\ +  13.867 * ICOR - 1.45 * status\\
status =
  \begin{cases}
    1 &amp; \text{if Developing Country}\\
    0 &amp; \text{if Developed Country}
  \end{cases}
\end{gather*}\]</span>
<p><em>Interactive model:</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                                    estimate std.error statistic   p.value
  &lt;chr&gt;                                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                               33.1      4.37        7.58 5.95e- 14
2 Schooling                                  1.16     0.0633     18.4  1.24e- 68
3 HIV.AIDS                                  -0.633    0.0179    -35.3  5.26e-204
4 StatusDeveloping                          14.3      4.42        3.24 1.20e-  3
5 Income.composition.of.resources           32.9      5.40        6.10 1.35e-  9
6 StatusDeveloping:Income.composition.of…  -19.0      5.31       -3.58 3.49e-  4</code></pre>
</div>
</div>
<span class="math display">\[\begin{gather*}
\widehat{LifeExpectancy} = 33.120 + 1.162 * schooling - 0.63*HIV/AIDS \\ +  32.927*ICOR + 14.33*status -19.025*ICOR*status\\
status =
  \begin{cases}
    1 &amp; \text{if Developing Country}\\
    0 &amp; \text{if Developed Country}
  \end{cases}
\end{gather*}\]</span>
<p><em>AIC Scores</em></p>
<p>Score [1] is the AIC score for the interactive model, and score [2] is the AIC score for the additive model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9453.634</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9464.471</code></pre>
</div>
</div>
<p>Both the additive and interactive models have similar AIC values. In the additive model, each predictor is added to the model individually, so the coefficient that comes out is the effect measured as if it were independent. The assumption made is that each factor has an independent effect on life expectancy. In the interactive model, there’s an “interaction term”, which examines the combined effect of income composition and a country’s development status on life expectancy. This allows us to measure how the relationship between income composition and life expectancy could be different in developing vs developed countries.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>In conclusion, we found that HIV/AIDs, Income Composition of Resources, and Schooling are the factors that have the greatest effect on the average life expectancy for a country in a given year, and this relationship holds true for both developing and developed countries.</p>
<p>We fit both an additive and interactive model to predict the average life expectancy of a country based on its HIV/AIDs deaths per 1,000 live births, Income Composition of Resources, Schooling, and Development Status. For our interactive model, we decided to add an interaction term between Income Composition of Resources and Development Status, because these two variables are likely to influence each other.</p>
<p>We also calculated the AIC scores for each model, which measure how well a given model fits the data with lower scores indicating a more appropriate model. The interactive and additive models have similar AIC values at 9453.634 and 9464.471, respectively. The interactive model has a lower AIC score, indicating that it is a more appropriate model for the data and a slightly better predictor of life expectancy than the additive model.</p>
<p>In the additive model, each predictor is added to the model individually, so the coefficient that comes out is the effect measured as if it were independent. The assumption made is that each factor has an independent effect on life expectancy. In the interactive model, there’s an “interaction term”, which examines the combined effect of income composition and a country’s development status on life expectancy. This allows us to measure how the relationship between income composition and life expectancy could be different in developing vs.&nbsp;developed countries, leading to a better fit model.</p>
<p><strong>Model interpretations</strong></p>
<p>Schooling:</p>
<ul>
<li><p>Additive Model: The coefficient of schooling is 1.195, implying that, with all other variables constant, a one-year increase in schooling is correlated with about an increase of 1.195 years of life expectancy.</p></li>
<li><p>Interactive model: The coefficient of schooling is 1.1624. Since in this model, schooling is not interacting with any other terms, it follows that the coefficient is similar to the additive model.</p></li>
</ul>
<p>HIV/AIDS:</p>
<ul>
<li><p>Additive Model: The coefficient for HIV/AIDS is -0.6307, indicating that a unit increase in HIV/AIDS prevalence is associated with a decrease of 0.6307 years in life expectancy.</p></li>
<li><p>Interactive model: The coefficient is -0.6327, which is close but slightly more negative. The coefficients are pretty close, indicating the impact HIV/AIDS prevalence has on life expectancy is similar in both models, which follows given it has no additional interaction in this model.</p></li>
</ul>
<p>Income Composition of Resources:</p>
<ul>
<li><p>Additive Model: The coefficient is 13.8667, meaning for each unit increase in the income composition of resources, life expectancy has a predicted increase of 13.8667 years.</p></li>
<li><p>Interactive Model: The coefficient is 32.9267. The much-larger coefficient is part of an interaction term with development status. It indicates that, for example, the benefits of higher income composition are more positive in developing countries.</p></li>
</ul>
<p>Development Status:</p>
<ul>
<li><p>Additive Model: The coefficient is -1.4515, indicating that being a developing country is associated with a decrease of -1.4515 years of life expectancy. Essentially, developing countries have slightly lower life expectancy than developed countries.</p></li>
<li><p>Interactive Model: The coefficient is 14.3391, meaning being a developing country is linked to an increase of life expectancy by 14.3391 years. The implication of the difference is that the disadvantage of development status is complex and varies based on income composition. High income composition can either mitigate or reverse the negative impact of being a developing country.</p></li>
</ul>
<p><strong>Scope of inference</strong></p>
<p>Since the World Health Organization life expectancy data was collected through observation, we can only conclude an associative relationship between HIV/AIDs, Income Composition of Resources, Schooling, and Development Status on life expectancy. We cannot conclude that these factors are causal.</p>
<p><strong>Discussion</strong></p>
<p>Through the course of this project, we’ve learned a lot about the factors that affect impact life expectancy, and how those trends differ between developing and developed countries. Some country factors, like schooling or HIV/AIDS prevalence, appear to have clearer positive or negative associations with life expectancy regardless of country status. However, other factors, such as the income composition of resources score, seem to be more greatly correlated with life expectancy for developing than developed countries. Although our limited scope of inference means that we cannot conclude the causation of any of these variables with life expectancy, it does provide some insight into possible avenues for improving population health that require further research and more robust statistical analysis. This can then better inform government policy making and procedures.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>